#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define PSP_WIDTH 512
#define PSP_HEIGHT 272
#define PSP_HALF_WIDTH (PSP_WIDTH / 2)
#define PSP_HALF_HEIGHT (PSP_HEIGHT / 2)
#define PSP_BUFFER_SIZE (PSP_WIDTH * PSP_HEIGHT)

#define SCRATCHPAD_START 0x00010000
#define SCRATCHPAD_END 0x00013FFF

#endif