#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define PSP_ACTUAL_WIDTH 480
#define PSP_WIDTH 512
#define PSP_HEIGHT 272
#define PSP_HALF_WIDTH (PSP_WIDTH / 2)
#define PSP_HALF_HEIGHT (PSP_HEIGHT / 2)
#define PSP_BUFFER_SIZE (PSP_WIDTH * PSP_HEIGHT)

#define SCRATCHPAD_START 0x00010000
#define SCRATCHPAD_END 0x00013FFF

// GU Commands
#define FINISH_CMD 0x0F
#define FRAME_BUFFER_PTR_CMD 0x9C
#define FRAME_BUFFER_WIDTH_CMD 0x9D
#define DEPTH_BUFFER_PTR_CMD 0x9E
#define DEPTH_BUFFER_WIDTH_CMD 0x9F
#define TRANSMISSION_SRC_BUFF_PTR_CMD 0xB2
#define TRANSMISSION_SRC_BUFF_WIDTH_CMD 0xB3
#define TRANSMISSION_DEST_BUFF_PTR_CMD 0xB4
#define TRANSMISSION_DEST_BUFF_WIDTH_CMD 0xB5

#endif